//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plossum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLineStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plossum.Resources.CommandLineStrings", typeof(CommandLineStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the specified file (&quot;{0}&quot;) is denied.
        /// </summary>
        internal static string AccessToTheSpecifiedFile0IsDenied {
            get {
                return ResourceManager.GetString("AccessToTheSpecifiedFile0IsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias &quot;{0}&quot; is invalid for option &quot;{1}&quot;; BoolFunction is set to {2} and the {3} option style is enabled which prohibits any name longer than one character.
        /// </summary>
        internal static string Alias0IsInvalidForOption1BoolFunctionIsSetTo2AndThe3OptionStyleIsEnabledWhichProhibitsAnyNameLongerThanOneCharacter {
            get {
                return ResourceManager.GetString("Alias0IsInvalidForOption1BoolFunctionIsSetTo2AndThe3OptionStyleIsEnabledWhichProh" +
                        "ibitsAnyNameLongerThanOneCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name &quot;{0}&quot; is already in use by another option.
        /// </summary>
        internal static string AliasName0IsAlreadyInUseByAnotherOption {
            get {
                return ResourceManager.GetString("AliasName0IsAlreadyInUseByAnotherOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the options {0} must be specified.
        /// </summary>
        internal static string AllOfTheOptions0MustBeSpecified {
            get {
                return ResourceManager.GetString("AllOfTheOptions0MustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be less than {1}.
        /// </summary>
        internal static string Arg0MustNotBeLessThan1 {
            get {
                return ResourceManager.GetString("Arg0MustNotBeLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero.
        /// </summary>
        internal static string ArgMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ArgMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be non-negative.
        /// </summary>
        internal static string ArgMustBeNonNegative {
            get {
                return ResourceManager.GetString("ArgMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment characters must not be changed while parse in progress.
        /// </summary>
        internal static string AssignmentCharactersMustNotBeChangedWhileParseInProgress {
            get {
                return ResourceManager.GetString("AssignmentCharactersMustNotBeChangedWhileParseInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the option {0} must be specified.
        /// </summary>
        internal static string AtLeastOneOfTheOption0MustBeSpecified {
            get {
                return ResourceManager.GetString("AtLeastOneOfTheOption0MustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most one of the options {0} may be specified at once.
        /// </summary>
        internal static string AtMostOneOfTheOptions0MayBeSpecifiedAtOnce {
            get {
                return ResourceManager.GetString("AtMostOneOfTheOptions0MayBeSpecifiedAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoolFunction can not be set to &apos;{0}&apos; for option with a name longer than one character when option style &apos;{1}&apos; is specified in the {2} attribute.
        /// </summary>
        internal static string BoolFunctionCanNotBeSetTo0ForOptionWithANameLongerThanOneCharacterWhenOptionStyle1IsSpecifiedInThe2Attribute {
            get {
                return ResourceManager.GetString("BoolFunctionCanNotBeSetTo0ForOptionWithANameLongerThanOneCharacterWhenOptionStyle" +
                        "1IsSpecifiedInThe2Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoolFunction may not be set to &apos;{0}&apos; when option style &apos;{1}&apos; is not specified in the {2} attribute.
        /// </summary>
        internal static string BoolFunctionMayNotBeSetTo0WhenOptionStyle1IsNotSpecifiedInThe2Attribute {
            get {
                return ResourceManager.GetString("BoolFunctionMayNotBeSetTo0WhenOptionStyle1IsNotSpecifiedInThe2Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoolFunction may not be set to &apos;{0}&apos; when option style &apos;{1}&apos; is specified in the {2} attribute.
        /// </summary>
        internal static string BoolFunctionMayNotBeSetTo0WhenOptionStyle1IsSpecifiedInThe2Attribute {
            get {
                return ResourceManager.GetString("BoolFunctionMayNotBeSetTo0WhenOptionStyle1IsSpecifiedInThe2Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in commandline.
        /// </summary>
        internal static string DefaultCommandLineExceptionErrorMessage {
            get {
                return ResourceManager.GetString("DefaultCommandLineExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing option name for switch on command line.
        /// </summary>
        internal static string DefaultMissingOptionNameExceptionMessage {
            get {
                return ResourceManager.GetString("DefaultMissingOptionNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty option name is not allowed.
        /// </summary>
        internal static string EmptyOptionNameIsNotAllowed {
            get {
                return ResourceManager.GetString("EmptyOptionNameIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of input.
        /// </summary>
        internal static string EndOfInput {
            get {
                return ResourceManager.GetString("EndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found (&quot;{0}&quot;).
        /// </summary>
        internal static string FileNotFound0 {
            get {
                return ResourceManager.GetString("FileNotFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; non-implemented group requirement specified.
        /// </summary>
        internal static string InternalErrorNonImplementedGroupRequirementSpecified {
            get {
                return ResourceManager.GetString("InternalErrorNonImplementedGroupRequirementSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; option specified in prohibition does not exist.
        /// </summary>
        internal static string InternalErrorOptionSpecifiedInProhibitionDoesNotExist {
            get {
                return ResourceManager.GetString("InternalErrorOptionSpecifiedInProhibitionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; Option.Value was set more than MaxOccurs number of times.
        /// </summary>
        internal static string InternalErrorOptionValueWasSetMoreThanMaxOccursNumberOfTimes {
            get {
                return ResourceManager.GetString("InternalErrorOptionValueWasSetMoreThanMaxOccursNumberOfTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; unimplemented BoolFunction {0} used in option &quot;{1}&quot;.
        /// </summary>
        internal static string InternalErrorUnimplementedBoolFunction0UsedInOption1 {
            get {
                return ResourceManager.GetString("InternalErrorUnimplementedBoolFunction0UsedInOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; Unimplemented token type returned to CommandLineParser.
        /// </summary>
        internal static string InternalErrorUnimplementedTokenTypeReturnedToCommandLineParser {
            get {
                return ResourceManager.GetString("InternalErrorUnimplementedTokenTypeReturnedToCommandLineParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; Unimplemented VerticalAlignment used.
        /// </summary>
        internal static string InternalErrorUnimplementedVerticalAlignmentUsed {
            get {
                return ResourceManager.GetString("InternalErrorUnimplementedVerticalAlignmentUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enumeration value &quot;{0}&quot;.
        /// </summary>
        internal static string InvalidEnumerationValue0 {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Id of group; Id must not be null or empty.
        /// </summary>
        internal static string InvalidIdOfGroupIdMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidIdOfGroupIdMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value ({0}) for option &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidValue0ForOption1 {
            get {
                return ResourceManager.GetString("InvalidValue0ForOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &quot;{0}&quot; for option &quot;{1}&quot;; The value must be one of {2}.
        /// </summary>
        internal static string InvalidValue0ForOption1TheValueMustBeOneOf2 {
            get {
                return ResourceManager.GetString("InvalidValue0ForOption1TheValueMustBeOneOf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or &quot;{0}&quot;.
        /// </summary>
        internal static string LastItemOfExclusiveList {
            get {
                return ResourceManager.GetString("LastItemOfExclusiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing quote.
        /// </summary>
        internal static string MissingClosingQuote {
            get {
                return ResourceManager.GetString("MissingClosingQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing quote for quoted value.
        /// </summary>
        internal static string MissingClosingQuoteForQuotedValue {
            get {
                return ResourceManager.GetString("MissingClosingQuoteForQuotedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing quote for quote command line value: {0}.
        /// </summary>
        internal static string MissingClosingQuoteForValue0 {
            get {
                return ResourceManager.GetString("MissingClosingQuoteForValue0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required attribute for a command line manager object: CommandLineManagerAttribute.
        /// </summary>
        internal static string MissingRequiredAttributeForACommandLineManagerObjectCommandLineManagerAttribute {
            get {
                return ResourceManager.GetString("MissingRequiredAttributeForACommandLineManagerObjectCommandLineManagerAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required option &quot;{0}&quot;..
        /// </summary>
        internal static string MissingRequiredOption0 {
            get {
                return ResourceManager.GetString("MissingRequiredOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required value for option &quot;{0}&quot;.
        /// </summary>
        internal static string MissingRequiredValueForOption0 {
            get {
                return ResourceManager.GetString("MissingRequiredValueForOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the options {0} must be specified.
        /// </summary>
        internal static string OneOfTheOptions0MustBeSpecified {
            get {
                return ResourceManager.GetString("OneOfTheOptions0MustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (on line {0} in {1}).
        /// </summary>
        internal static string OnLine0InFile1 {
            get {
                return ResourceManager.GetString("OnLine0InFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} occurence(s) of option &quot;{1}&quot; found; it must be specified at least {2} time(s).
        /// </summary>
        internal static string Only0OccurenceSOfOption1FoundItMustBeSpecifiedAtLeast2TimeS {
            get {
                return ResourceManager.GetString("Only0OccurenceSOfOption1FoundItMustBeSpecifiedAtLeast2TimeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} occurence(s) of option &quot;{1}&quot; found; it must be specified exactly {2} time(s).
        /// </summary>
        internal static string Only0OccurenceSOfOption1FoundItMustBeSpecifiedExactly2TimeS {
            get {
                return ResourceManager.GetString("Only0OccurenceSOfOption1FoundItMustBeSpecifiedExactly2TimeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one of the options {0} may be specified.
        /// </summary>
        internal static string OnlyOneOfTheOptions0MayBeSpecified {
            get {
                return ResourceManager.GetString("OnlyOneOfTheOptions0MayBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; does not accept a value.
        /// </summary>
        internal static string Option0DoesNotAcceptAValue {
            get {
                return ResourceManager.GetString("Option0DoesNotAcceptAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; may not be specified together with option &quot;{1}&quot;.
        /// </summary>
        internal static string Option0MayNotBeSpecifiedTogetherWithOption1 {
            get {
                return ResourceManager.GetString("Option0MayNotBeSpecifiedTogetherWithOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; must not be specified more than {1} times.
        /// </summary>
        internal static string Option0MustNotBeSpecifiedMoreThan1Times {
            get {
                return ResourceManager.GetString("Option0MustNotBeSpecifiedMoreThan1Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; must not be specified multiple times.
        /// </summary>
        internal static string Option0MustNotBeSpecifiedMultipleTimes {
            get {
                return ResourceManager.GetString("Option0MustNotBeSpecifiedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of command line option with parameter name &quot;{0}&quot; ({1}).
        /// </summary>
        internal static string RedefinitionOfCommandLineOptionWithParameterName01 {
            get {
                return ResourceManager.GetString("RedefinitionOfCommandLineOptionWithParameterName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of group with id &quot;{0}&quot; ({1}).
        /// </summary>
        internal static string RedefinitionOfGroupWithId01 {
            get {
                return ResourceManager.GetString("RedefinitionOfGroupWithId01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path (&quot;{0}&quot;) is invalid.
        /// </summary>
        internal static string TheSpecifiedPath0IsInvalid {
            get {
                return ResourceManager.GetString("TheSpecifiedPath0IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path (&quot;{0}&quot;) is too long.
        /// </summary>
        internal static string TheSpecifiedPath0IsTooLong {
            get {
                return ResourceManager.GetString("TheSpecifiedPath0IsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined option &quot;{0}&quot; referenced from prohibition section of option &quot;{1}&quot;.
        /// </summary>
        internal static string UndefinedOption0ReferencedFromProhibitionSectionOfOption1 {
            get {
                return ResourceManager.GetString("UndefinedOption0ReferencedFromProhibitionSectionOfOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected &apos;{0}&apos; character on command line.
        /// </summary>
        internal static string Unexpected0CharacterOnCommandLine {
            get {
                return ResourceManager.GetString("Unexpected0CharacterOnCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of string.
        /// </summary>
        internal static string UnexpectedEndOfString {
            get {
                return ResourceManager.GetString("UnexpectedEndOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option &quot;{0}&quot;.
        /// </summary>
        internal static string UnknownOption0 {
            get {
                return ResourceManager.GetString("UnknownOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using case insensitive names.
        /// </summary>
        internal static string UsingCaseInsensitiveNames {
            get {
                return ResourceManager.GetString("UsingCaseInsensitiveNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using case sensitive names.
        /// </summary>
        internal static string UsingCaseSensitiveNames {
            get {
                return ResourceManager.GetString("UsingCaseSensitiveNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specified for &quot;{0}&quot; ({3}) is out of range; expected a numeric value between {1} and {2}.
        /// </summary>
        internal static string ValueFor03OutOfRangeExpectedNumericBetween1And2 {
            get {
                return ResourceManager.GetString("ValueFor03OutOfRangeExpectedNumericBetween1And2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for this option type.
        /// </summary>
        internal static string ValueWasEitherTooLargeOrTooSmallForThisOptionType {
            get {
                return ResourceManager.GetString("ValueWasEitherTooLargeOrTooSmallForThisOptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width must not be less than {0}.
        /// </summary>
        internal static string WidthMustNotBeLessThan0 {
            get {
                return ResourceManager.GetString("WidthMustNotBeLessThan0", resourceCulture);
            }
        }
    }
}
