
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class HistoryWidget
	{
		private global::Gtk.VBox vboxHistoryItems;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.HistoryWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.HistoryWidget";
			// Container child BlinkStickClient.HistoryWidget.Gtk.Container+ContainerChild
			this.vboxHistoryItems = new global::Gtk.VBox ();
			this.vboxHistoryItems.Name = "vboxHistoryItems";
			this.vboxHistoryItems.Spacing = 6;
			this.vboxHistoryItems.BorderWidth = ((uint)(12));
			this.Add (this.vboxHistoryItems);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
