
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class HelpWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.HelpWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.HelpWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
