
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStick
{
	public partial class BlinkstickServiceSettingsWidget
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Button buttonPaste;
		
		private global::Gtk.Entry entryAccessCode;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStick.BlinkstickServiceSettingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStick.BlinkstickServiceSettingsWidget";
			// Container child BlinkStick.BlinkstickServiceSettingsWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.buttonPaste = new global::Gtk.Button ();
			this.buttonPaste.CanFocus = true;
			this.buttonPaste.Name = "buttonPaste";
			this.buttonPaste.UseUnderline = true;
			this.buttonPaste.Label = global::Mono.Unix.Catalog.GetString ("Paste");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-paste", global::Gtk.IconSize.Menu);
			this.buttonPaste.Image = w1;
			this.table1.Add (this.buttonPaste);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonPaste]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryAccessCode = new global::Gtk.Entry ();
			this.entryAccessCode.CanFocus = true;
			this.entryAccessCode.Name = "entryAccessCode";
			this.entryAccessCode.IsEditable = true;
			this.entryAccessCode.InvisibleChar = '●';
			this.table1.Add (this.entryAccessCode);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryAccessCode]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Access Code:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonPaste.Clicked += new global::System.EventHandler (this.OnButtonPasteClicked);
		}
	}
}
