
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class BlinkStickEmulatorWidget
	{
		private global::Gtk.VBox vboxMain;
		
		private global::Gtk.DrawingArea drawingareaMain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.BlinkStickEmulatorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.BlinkStickEmulatorWidget";
			// Container child BlinkStickClient.BlinkStickEmulatorWidget.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.drawingareaMain = new global::Gtk.DrawingArea ();
			this.drawingareaMain.Name = "drawingareaMain";
			this.vboxMain.Add (this.drawingareaMain);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.drawingareaMain]));
			w1.Position = 0;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
