
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStick
{
	public partial class EditNotificationForm
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.Table tableControls;
		private global::Gtk.CheckButton checkbuttonEnabled;
		private global::Gtk.ComboBox comboboxBlinkSpeed;
		private global::Gtk.ComboBox comboboxDevices;
		private global::Gtk.ComboBox comboboxPriority;
		private global::Gtk.Entry entryName;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ColorButton colorbuttonColor;
		private global::Gtk.HBox hbox2;
		private global::Gtk.SpinButton spinbuttonBlinkCount;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label4;
		private global::Gtk.Label labelBlinkSPeed;
		private global::Gtk.Label labelColor;
		private global::Gtk.Label labelName;
		private global::Gtk.Label labelPriority;
		private global::Gtk.VBox vbox2;
		private global::Gtk.RadioButton radiobuttonBlink;
		private global::Gtk.RadioButton radiobuttonPulse;
		private global::Gtk.RadioButton radiobuttonMorph;
		private global::Gtk.Label label3;
		private global::Gtk.Button buttonTest;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStick.EditNotificationForm
			this.Name = "BlinkStick.EditNotificationForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("Notifications Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child BlinkStick.EditNotificationForm.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.tableControls = new global::Gtk.Table (((uint)(8)), ((uint)(2)), false);
			this.tableControls.Name = "tableControls";
			this.tableControls.RowSpacing = ((uint)(6));
			this.tableControls.ColumnSpacing = ((uint)(6));
			this.tableControls.BorderWidth = ((uint)(12));
			// Container child tableControls.Gtk.Table+TableChild
			this.checkbuttonEnabled = new global::Gtk.CheckButton ();
			this.checkbuttonEnabled.CanFocus = true;
			this.checkbuttonEnabled.Name = "checkbuttonEnabled";
			this.checkbuttonEnabled.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
			this.checkbuttonEnabled.DrawIndicator = true;
			this.checkbuttonEnabled.UseUnderline = true;
			this.tableControls.Add (this.checkbuttonEnabled);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableControls [this.checkbuttonEnabled]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.comboboxBlinkSpeed = global::Gtk.ComboBox.NewText ();
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Very Very Fast"));
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Very Fast"));
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Fast"));
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Slow"));
			this.comboboxBlinkSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Very Slow"));
			this.comboboxBlinkSpeed.Name = "comboboxBlinkSpeed";
			this.tableControls.Add (this.comboboxBlinkSpeed);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableControls [this.comboboxBlinkSpeed]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.comboboxDevices = global::Gtk.ComboBox.NewText ();
			this.comboboxDevices.Name = "comboboxDevices";
			this.tableControls.Add (this.comboboxDevices);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableControls [this.comboboxDevices]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.comboboxPriority = global::Gtk.ComboBox.NewText ();
			this.comboboxPriority.AppendText (global::Mono.Unix.Catalog.GetString ("Low"));
			this.comboboxPriority.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.comboboxPriority.AppendText (global::Mono.Unix.Catalog.GetString ("High"));
			this.comboboxPriority.Name = "comboboxPriority";
			this.tableControls.Add (this.comboboxPriority);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableControls [this.comboboxPriority]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.entryName = new global::Gtk.Entry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.tableControls.Add (this.entryName);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableControls [this.entryName]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.colorbuttonColor = new global::Gtk.ColorButton ();
			this.colorbuttonColor.CanFocus = true;
			this.colorbuttonColor.Events = ((global::Gdk.EventMask)(784));
			this.colorbuttonColor.Name = "colorbuttonColor";
			this.colorbuttonColor.Xalign = 1F;
			this.hbox1.Add (this.colorbuttonColor);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.colorbuttonColor]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.tableControls.Add (this.hbox1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableControls [this.hbox1]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spinbuttonBlinkCount = new global::Gtk.SpinButton (1D, 10D, 1D);
			this.spinbuttonBlinkCount.CanFocus = true;
			this.spinbuttonBlinkCount.Name = "spinbuttonBlinkCount";
			this.spinbuttonBlinkCount.Adjustment.PageIncrement = 2D;
			this.spinbuttonBlinkCount.ClimbRate = 1D;
			this.spinbuttonBlinkCount.Numeric = true;
			this.spinbuttonBlinkCount.Value = 1D;
			this.hbox2.Add (this.spinbuttonBlinkCount);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spinbuttonBlinkCount]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.tableControls.Add (this.hbox2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableControls [this.hbox2]));
			w10.TopAttach = ((uint)(6));
			w10.BottomAttach = ((uint)(7));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Ypad = 3;
			this.label1.Xalign = 0F;
			this.label1.Yalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Blink Type:");
			this.tableControls.Add (this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableControls [this.label1]));
			w11.TopAttach = ((uint)(7));
			w11.BottomAttach = ((uint)(8));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Blinks:");
			this.tableControls.Add (this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableControls [this.label2]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Device:");
			this.tableControls.Add (this.label4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableControls [this.label4]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.labelBlinkSPeed = new global::Gtk.Label ();
			this.labelBlinkSPeed.Name = "labelBlinkSPeed";
			this.labelBlinkSPeed.Xalign = 0F;
			this.labelBlinkSPeed.LabelProp = global::Mono.Unix.Catalog.GetString ("Blink Speed:");
			this.tableControls.Add (this.labelBlinkSPeed);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableControls [this.labelBlinkSPeed]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.labelColor = new global::Gtk.Label ();
			this.labelColor.Name = "labelColor";
			this.labelColor.Xalign = 0F;
			this.labelColor.LabelProp = global::Mono.Unix.Catalog.GetString ("Color:");
			this.tableControls.Add (this.labelColor);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableControls [this.labelColor]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.Xalign = 0F;
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("Event Name:");
			this.tableControls.Add (this.labelName);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableControls [this.labelName]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.labelPriority = new global::Gtk.Label ();
			this.labelPriority.Name = "labelPriority";
			this.labelPriority.Xalign = 0F;
			this.labelPriority.LabelProp = global::Mono.Unix.Catalog.GetString ("Priority:");
			this.tableControls.Add (this.labelPriority);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableControls [this.labelPriority]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableControls.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobuttonBlink = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Blink"));
			this.radiobuttonBlink.CanFocus = true;
			this.radiobuttonBlink.Name = "radiobuttonBlink";
			this.radiobuttonBlink.DrawIndicator = true;
			this.radiobuttonBlink.UseUnderline = true;
			this.radiobuttonBlink.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox2.Add (this.radiobuttonBlink);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobuttonBlink]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobuttonPulse = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Pulse"));
			this.radiobuttonPulse.CanFocus = true;
			this.radiobuttonPulse.Name = "radiobuttonPulse";
			this.radiobuttonPulse.DrawIndicator = true;
			this.radiobuttonPulse.UseUnderline = true;
			this.radiobuttonPulse.Group = this.radiobuttonBlink.Group;
			this.vbox2.Add (this.radiobuttonPulse);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobuttonPulse]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobuttonMorph = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Morph"));
			this.radiobuttonMorph.CanFocus = true;
			this.radiobuttonMorph.Name = "radiobuttonMorph";
			this.radiobuttonMorph.DrawIndicator = true;
			this.radiobuttonMorph.UseUnderline = true;
			this.radiobuttonMorph.Group = this.radiobuttonBlink.Group;
			this.vbox2.Add (this.radiobuttonMorph);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobuttonMorph]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.tableControls.Add (this.vbox2);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableControls [this.vbox2]));
			w21.TopAttach = ((uint)(7));
			w21.BottomAttach = ((uint)(8));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.tableControls);
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.tableControls, this.label3);
			this.label3.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Internal child BlinkStick.EditNotificationForm.ActionArea
			global::Gtk.HButtonBox w24 = this.ActionArea;
			w24.Name = "dialog1_ActionArea";
			w24.Spacing = 10;
			w24.BorderWidth = ((uint)(5));
			w24.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonTest = new global::Gtk.Button ();
			this.buttonTest.CanFocus = true;
			this.buttonTest.Name = "buttonTest";
			this.buttonTest.UseUnderline = true;
			this.buttonTest.Label = global::Mono.Unix.Catalog.GetString ("Test");
			this.AddActionWidget (this.buttonTest, -10);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonTest]));
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonCancel]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonOk]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 352;
			this.DefaultHeight = 430;
			this.Show ();
		}
	}
}
