
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class PatternDialog
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action newAction;
		
		private global::Gtk.Action deleteAction;
		
		private global::Gtk.Action propertiesAction;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox3;
		
		private global::BlinkStickClient.BlinkStickEmulatorWidget blinkstickemulatorwidget1;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeviewPatterns;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label labelPattern;
		
		private global::Gtk.ScrolledWindow scrolledwindowAnimations;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.PatternDialog
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
			w1.Add (this.newAction, null);
			this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
			w1.Add (this.deleteAction, null);
			this.propertiesAction = new global::Gtk.Action ("propertiesAction", null, null, "gtk-properties");
			w1.Add (this.propertiesAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "BlinkStickClient.PatternDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child BlinkStickClient.PatternDialog.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.blinkstickemulatorwidget1 = new global::BlinkStickClient.BlinkStickEmulatorWidget ();
			this.blinkstickemulatorwidget1.Events = ((global::Gdk.EventMask)(256));
			this.blinkstickemulatorwidget1.Name = "blinkstickemulatorwidget1";
			this.vbox3.Add (this.blinkstickemulatorwidget1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.blinkstickemulatorwidget1]));
			w3.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'><toolitem name=\'newAction\' action=\'newAction\'/><tool" +
			"item name=\'propertiesAction\' action=\'propertiesAction\'/><toolitem name=\'deleteAc" +
			"tion\' action=\'deleteAction\'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox3.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewPatterns = new global::Gtk.TreeView ();
			this.treeviewPatterns.CanFocus = true;
			this.treeviewPatterns.Name = "treeviewPatterns";
			this.treeviewPatterns.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this.treeviewPatterns);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w6.Position = 2;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(6));
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelPattern = new global::Gtk.Label ();
			this.labelPattern.Name = "labelPattern";
			this.labelPattern.LabelProp = global::Mono.Unix.Catalog.GetString ("Pattern Animation");
			this.vbox4.Add (this.labelPattern);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelPattern]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindowAnimations = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowAnimations.WidthRequest = 300;
			this.scrolledwindowAnimations.CanFocus = true;
			this.scrolledwindowAnimations.Name = "scrolledwindowAnimations";
			this.scrolledwindowAnimations.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindowAnimations.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowAnimations.Gtk.Container+ContainerChild
			global::Gtk.Viewport w9 = new global::Gtk.Viewport ();
			w9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.BorderWidth = ((uint)(6));
			w9.Add (this.vbox2);
			this.scrolledwindowAnimations.Add (w9);
			this.vbox4.Add (this.scrolledwindowAnimations);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindowAnimations]));
			w12.Position = 1;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w2 [this.hbox1]));
			w14.Position = 0;
			// Internal child BlinkStickClient.PatternDialog.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-close";
			this.AddActionWidget (this.buttonCancel, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.buttonCancel]));
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 673;
			this.DefaultHeight = 514;
			this.Show ();
			this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
			this.deleteAction.Activated += new global::System.EventHandler (this.OnDeleteActionActivated);
			this.propertiesAction.Activated += new global::System.EventHandler (this.OnPropertiesActionActivated);
			this.treeviewPatterns.CursorChanged += new global::System.EventHandler (this.OnTreeviewPatternsCursorChanged);
			this.treeviewPatterns.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeviewPatternsRowActivated);
		}
	}
}
