
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class GoogleEmailSettingsWidget
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry entryPassword;
		
		private global::Gtk.Entry entryUsername;
		
		private global::Gtk.Label labelGmailUsername;
		
		private global::Gtk.Label labelPassword;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.GoogleEmailSettingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.GoogleEmailSettingsWidget";
			// Container child BlinkStickClient.GoogleEmailSettingsWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.Visibility = false;
			this.entryPassword.InvisibleChar = '●';
			this.table1.Add (this.entryPassword);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPassword]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryUsername = new global::Gtk.Entry ();
			this.entryUsername.CanFocus = true;
			this.entryUsername.Name = "entryUsername";
			this.entryUsername.IsEditable = true;
			this.entryUsername.InvisibleChar = '●';
			this.table1.Add (this.entryUsername);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryUsername]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelGmailUsername = new global::Gtk.Label ();
			this.labelGmailUsername.Name = "labelGmailUsername";
			this.labelGmailUsername.Xalign = 0F;
			this.labelGmailUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Gmail Username:");
			this.table1.Add (this.labelGmailUsername);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelGmailUsername]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelPassword = new global::Gtk.Label ();
			this.labelPassword.Name = "labelPassword";
			this.labelPassword.Xalign = 0F;
			this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.table1.Add (this.labelPassword);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelPassword]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
