
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class KeyboardEditorWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton checkbuttonCtrl;
		
		private global::Gtk.CheckButton checkbuttonAlt;
		
		private global::Gtk.CheckButton checkbuttonWin;
		
		private global::Gtk.ComboBox comboboxKey;
		
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.KeyboardEditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.KeyboardEditorWidget";
			// Container child BlinkStickClient.KeyboardEditorWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkbuttonCtrl = new global::Gtk.CheckButton ();
			this.checkbuttonCtrl.CanFocus = true;
			this.checkbuttonCtrl.Name = "checkbuttonCtrl";
			this.checkbuttonCtrl.Label = global::Mono.Unix.Catalog.GetString ("Ctrl");
			this.checkbuttonCtrl.DrawIndicator = true;
			this.checkbuttonCtrl.UseUnderline = true;
			this.hbox1.Add (this.checkbuttonCtrl);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbuttonCtrl]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkbuttonAlt = new global::Gtk.CheckButton ();
			this.checkbuttonAlt.CanFocus = true;
			this.checkbuttonAlt.Name = "checkbuttonAlt";
			this.checkbuttonAlt.Label = global::Mono.Unix.Catalog.GetString ("Alt");
			this.checkbuttonAlt.DrawIndicator = true;
			this.checkbuttonAlt.UseUnderline = true;
			this.hbox1.Add (this.checkbuttonAlt);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbuttonAlt]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkbuttonWin = new global::Gtk.CheckButton ();
			this.checkbuttonWin.CanFocus = true;
			this.checkbuttonWin.Name = "checkbuttonWin";
			this.checkbuttonWin.Label = global::Mono.Unix.Catalog.GetString ("Win");
			this.checkbuttonWin.DrawIndicator = true;
			this.checkbuttonWin.UseUnderline = true;
			this.hbox1.Add (this.checkbuttonWin);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbuttonWin]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboboxKey = global::Gtk.ComboBox.NewText ();
			this.comboboxKey.Name = "comboboxKey";
			this.hbox1.Add (this.comboboxKey);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxKey]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Configure Keyboard Shortcut</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
