
// This file has been generated by the GUI designer. Do not modify.
namespace BlinkStickClient
{
	public partial class MoodlightEditorWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox comboboxTransitionSpeed;
		
		private global::Gtk.Label GtkLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlinkStickClient.MoodlightEditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BlinkStickClient.MoodlightEditorWidget";
			// Container child BlinkStickClient.MoodlightEditorWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Transition speed:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboboxTransitionSpeed = global::Gtk.ComboBox.NewText ();
			this.comboboxTransitionSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Slow"));
			this.comboboxTransitionSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.comboboxTransitionSpeed.AppendText (global::Mono.Unix.Catalog.GetString ("Fast"));
			this.comboboxTransitionSpeed.Name = "comboboxTransitionSpeed";
			this.hbox1.Add (this.comboboxTransitionSpeed);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxTransitionSpeed]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Moodlight settings</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
